vich_uploader:
    db_driver: orm

    mappings:
        terrain_directory:
            uri_prefix: /uploads/terrain
            upload_destination: '%kernel.project_dir%/public/uploads/terrain'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
