vich_uploader:
    db_driver: orm

    mappings:
        produit_directory:
                uri_prefix: /uploads/produit
                upload_destination: '%kernel.project_dir%/public/uploads/produit'
                namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

                inject_on_load: false
                delete_on_update: true
                delete_on_remove: true

    