vich_uploader:
    db_driver: orm

    mappings:
        image:
            uri_prefix: /uploads/
            upload_destination: '%kernel.project_dir%/public/uploads/'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            delete_on_remove: true
            delete_on_update: true